apiVersion: v1
kind: Service
metadata:
  name: core-services
spec:
  selector: { app: core-services }
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  type: {{ .Values.service.type }}
