apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-services
spec:
  replicas: 1
  selector:
    matchLabels: { app: core-services }
  template:
    metadata:
      labels: { app: core-services }
    spec:
      containers:
        - name: core-services
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports: [{ containerPort: 8080 }]
